// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStuxNxUpnXzIliKlNJOxSWdoMEY3eNac',
    appId: '1:184031572919:web:ede04a0ab9174aca136e32',
    messagingSenderId: '184031572919',
    projectId: 'fcmsample-fadf7',
    authDomain: 'fcmsample-fadf7.firebaseapp.com',
    storageBucket: 'fcmsample-fadf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjtMKv3jlydfPA2G_TfU3hHUq5Qds7bWA',
    appId: '1:184031572919:android:66b73217c29888b0136e32',
    messagingSenderId: '184031572919',
    projectId: 'fcmsample-fadf7',
    storageBucket: 'fcmsample-fadf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJT77uWihW6dPMKEgAh8G-aN-3FpWUmfk',
    appId: '1:184031572919:ios:30d350a3b8323739136e32',
    messagingSenderId: '184031572919',
    projectId: 'fcmsample-fadf7',
    storageBucket: 'fcmsample-fadf7.appspot.com',
    iosBundleId: 'com.example.fcmSampleMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJT77uWihW6dPMKEgAh8G-aN-3FpWUmfk',
    appId: '1:184031572919:ios:2b0f7eeb8c508ea8136e32',
    messagingSenderId: '184031572919',
    projectId: 'fcmsample-fadf7',
    storageBucket: 'fcmsample-fadf7.appspot.com',
    iosBundleId: 'com.example.fcmSampleMessaging.RunnerTests',
  );
}
